# Logistic Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('../input/mobile-price-classification/train.csv')
data_test = pd.read_csv('../input/mobile-price-classification/test.csv')
data_test = data_test.drop('id', axis=1)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [4]:
print(X_train)

[[5.310e+02 0.000e+00 1.100e+00 ... 0.000e+00 1.000e+00 0.000e+00]
 [7.640e+02 1.000e+00 1.200e+00 ... 1.000e+00 1.000e+00 0.000e+00]
 [1.812e+03 1.000e+00 1.300e+00 ... 1.000e+00 1.000e+00 1.000e+00]
 ...
 [1.190e+03 0.000e+00 2.000e+00 ... 0.000e+00 0.000e+00 1.000e+00]
 [1.191e+03 0.000e+00 2.400e+00 ... 1.000e+00 1.000e+00 1.000e+00]
 [7.060e+02 0.000e+00 5.000e-01 ... 1.000e+00 0.000e+00 1.000e+00]]


In [5]:
print(y_train)

[2 2 3 ... 3 0 1]


In [6]:
print(X_test)

[[1.454e+03 1.000e+00 5.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]
 [1.092e+03 1.000e+00 5.000e-01 ... 0.000e+00 1.000e+00 0.000e+00]
 [1.524e+03 1.000e+00 1.800e+00 ... 1.000e+00 0.000e+00 1.000e+00]
 ...
 [1.759e+03 1.000e+00 1.400e+00 ... 1.000e+00 1.000e+00 0.000e+00]
 [5.140e+02 1.000e+00 1.600e+00 ... 1.000e+00 1.000e+00 1.000e+00]
 [1.410e+03 1.000e+00 5.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]]


In [7]:
print(y_test)

[3 0 2 2 2 0 0 3 3 1 1 3 0 2 3 0 3 2 2 1 0 0 3 1 2 2 3 1 3 1 1 0 2 0 1 3 0
 0 3 3 3 1 3 3 1 3 0 1 3 1 1 3 0 3 0 3 2 2 0 3 3 1 3 2 1 2 3 2 2 2 3 2 1 0
 1 3 2 2 1 2 3 3 3 0 0 0 2 1 2 3 1 2 2 1 0 3 3 3 0 3 1 1 2 1 3 2 2 3 2 3 3
 0 0 1 3 3 0 0 1 0 0 3 2 2 1 1 1 1 0 2 1 3 2 3 3 3 3 2 0 1 1 2 1 3 1 3 0 0
 2 0 1 1 1 1 3 0 0 3 1 3 2 1 3 1 2 3 3 2 1 0 3 1 2 3 3 0 2 2 3 0 2 1 0 1 2
 1 2 0 3 3 1 1 0 2 3 0 1 2 2 0 3 3 3 1 2 3 3 3 0 0 0 2 3 3 0 0 1 3 1 3 3 3
 0 0 2 3 3 1 0 2 0 0 0 3 2 0 2 2 1 1 0 2 3 3 0 0 1 3 3 2 3 0 3 1 1 0 2 3 3
 2 0 0 1 2 3 2 2 3 2 1 0 3 3 2 1 3 2 2 2 1 0 2 2 1 0 0 2 2 2 2 0 1 3 0 1 2
 3 0 2 0 1 1 3 0 0 2 3 1 2 0 2 0 3 0 3 3 2 3 1 2 2 1 1 1 0 1 0 3 1 0 3 0 0
 1 3 0 3 1 2 0 1 3 0 2 2 1 2 1 1 0 2 0 0 3 1 2 3 2 2 0 3 2 2 1 3 2 3 3 3 0
 2 0 3 0 1 1 2 2 1 3 1 2 0 1 2 3 0 0 1 3 0 3 0 2 2 1 1 0 2 1 0 1 3 0 3 3 0
 2 1 3 1 1 3 2 0 3 2 2 0 0 3 0 1 1 1 3 2 3 2 0 3 0 0 1 3 0 0 3 2 2 2 3 0 0
 1 2 1 2 0 3 3 0 3 3 0 2 2 1 0 2 2 1 3 2 2 0 2 0 3 3 2 1 0 3 1 2 0 0 1 3 0
 3 0 0 2 2 0 1 3 0 3 2 1 

In [8]:
print(data_test.head())

   battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0           1043     1          1.8         1  14       0           5    0.1   
1            841     1          0.5         1   4       1          61    0.8   
2           1807     1          2.8         0   1       0          27    0.9   
3           1546     0          0.5         1  18       1          25    0.5   
4           1434     0          1.4         0  11       1          49    0.5   

   mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        193        3  16        226      1412  3476    12     7          2   
1        191        5  12        746       857  3895     6     0          7   
2        186        3   4       1270      1366  2396    17    10         10   
3         96        8  20        295      1752  3893    10     0          7   
4        108        6  18        749       810  1773    15     8          7   

   three_g  touch_screen  wifi  
0        0 

## Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
data_test = sc.fit_transform(data_test)

In [10]:
print(X_train)

[[-1.58954736 -0.97628121 -0.54409463 ... -1.77951304  1.01072417
  -1.02840321]
 [-1.06204271  1.02429504 -0.42202734 ...  0.56195149  1.01072417
  -1.02840321]
 [ 1.31059626  1.02429504 -0.29996004 ...  0.56195149  1.01072417
   0.97238125]
 ...
 [-0.09759213 -0.97628121  0.55451104 ... -1.77951304 -0.98938962
   0.97238125]
 [-0.09532817 -0.97628121  1.04278023 ...  0.56195149  1.01072417
   0.97238125]
 [-1.19335288 -0.97628121 -1.27649842 ...  0.56195149 -0.98938962
   0.97238125]]


In [11]:
print(X_test)

[[ 0.50009554  1.02429504 -1.27649842 ...  0.56195149  1.01072417
  -1.02840321]
 [-0.31946105  1.02429504 -1.27649842 ... -1.77951304  1.01072417
  -1.02840321]
 [ 0.65857334  1.02429504  0.31037645 ...  0.56195149 -0.98938962
   0.97238125]
 ...
 [ 1.19060593  1.02429504 -0.17789274 ...  0.56195149  1.01072417
  -1.02840321]
 [-1.62803483  1.02429504  0.06624185 ...  0.56195149  1.01072417
   0.97238125]
 [ 0.40048093  1.02429504 -1.27649842 ...  0.56195149  1.01072417
  -1.02840321]]


## Training the Logistic Regression model on the Training set

In [12]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Predicting the Test set results

In [13]:
y_pred = classifier.predict(X_test)

## Making the Confusion Matrix

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[122   2   0   0]
 [  3 103   4   0]
 [  0   5 116   4]
 [  0   0   1 140]]


0.962

# predicting test dataset

In [15]:
test_pred = classifier.predict(data_test)
print(test_pred)

[2 3 2 3 1 3 3 1 3 0 3 3 0 0 2 0 2 1 3 2 1 3 1 1 3 0 2 0 3 0 2 0 3 0 1 1 3
 1 2 1 1 2 0 0 0 1 0 3 1 2 1 0 2 0 3 0 3 1 1 3 3 3 0 1 1 1 2 3 1 2 1 2 2 3
 3 0 2 0 1 3 0 3 3 0 3 0 3 1 3 0 1 2 2 1 2 1 1 2 1 2 1 0 0 3 0 2 0 1 2 3 3
 2 1 3 3 3 3 2 3 0 0 3 2 1 2 0 3 2 2 2 0 2 2 1 3 1 1 0 3 2 1 2 1 3 2 3 3 3
 2 3 2 3 1 0 3 2 3 3 3 3 3 2 3 3 3 3 1 0 3 0 0 0 2 1 0 1 0 0 1 2 1 0 0 1 1
 2 2 1 0 0 0 1 0 3 1 0 2 2 2 3 1 2 2 2 3 2 2 1 0 0 1 2 0 2 3 3 0 2 0 3 2 3
 3 1 0 1 0 3 0 1 0 2 2 1 3 1 2 0 3 1 2 0 0 2 1 3 3 3 1 1 3 0 0 2 3 3 1 3 1
 1 3 2 1 2 3 3 3 1 0 0 2 3 1 1 3 2 1 3 0 0 2 0 0 3 2 3 3 2 1 3 3 2 3 1 2 1
 2 0 2 3 1 0 0 3 0 3 0 1 2 0 2 3 1 3 2 2 1 2 0 0 0 1 3 2 0 0 0 3 2 0 2 3 1
 2 2 2 3 1 3 3 1 2 2 3 3 0 3 0 3 1 3 1 2 3 0 1 0 3 1 3 2 3 0 0 0 0 2 0 0 2
 2 1 2 2 2 0 1 0 0 3 2 0 3 1 2 2 1 2 3 1 1 2 2 1 2 0 1 1 0 3 2 0 0 1 0 0 1
 1 0 1 0 2 2 3 2 3 0 3 0 3 0 1 1 0 1 0 3 2 3 3 1 3 1 3 1 2 2 0 1 2 1 1 0 0
 0 1 2 1 0 3 2 0 2 2 0 0 3 1 2 0 2 3 3 0 3 0 2 3 2 3 0 2 0 2 2 0 1 1 0 0 1
 2 1 3 3 3 2 3 1 2 2 3 3 

## Training the K-NN model on the Training set

In [16]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

## Predicting the Test set results

In [17]:
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix

In [18]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[84 36  3  1]
 [37 50 19  4]
 [14 46 49 16]
 [ 0 13 62 66]]


0.498

# predicting test dataset

In [19]:
test_pred = classifier.predict(data_test)
print(test_pred)

[2 3 1 3 1 3 3 1 2 0 3 2 0 1 0 0 1 1 2 2 2 3 0 1 3 1 1 0 2 1 1 2 3 1 1 1 2
 0 3 2 1 1 0 0 0 0 0 1 2 2 2 1 2 0 1 0 3 1 0 2 3 2 1 1 1 0 1 1 1 2 0 1 3 1
 3 0 1 1 2 3 0 2 3 0 3 0 2 1 1 1 2 3 0 0 0 0 0 1 0 2 0 1 0 3 1 1 0 1 1 2 3
 0 1 3 3 2 2 2 2 2 0 3 0 2 1 1 2 2 2 1 0 1 1 2 2 0 1 1 3 2 1 2 1 2 3 2 2 3
 2 1 1 3 1 2 1 3 3 2 2 3 2 2 2 1 3 2 1 0 3 0 0 0 1 1 0 1 2 0 0 1 1 0 0 1 0
 3 1 2 0 0 0 0 2 3 0 2 2 1 1 1 0 1 3 1 2 2 1 1 0 0 1 1 0 3 3 2 0 2 0 1 1 0
 2 1 0 2 1 2 0 0 1 2 1 2 1 1 2 0 3 0 1 0 0 2 1 2 2 3 1 1 3 0 0 3 2 3 1 3 2
 1 3 1 0 2 2 1 3 0 0 0 0 1 1 0 3 2 2 3 0 2 1 0 0 3 2 3 2 2 1 2 2 0 3 0 1 0
 2 0 1 1 1 0 1 3 0 3 0 0 1 1 1 2 0 2 3 3 0 3 0 0 1 0 2 3 1 1 0 2 1 0 1 3 1
 2 1 1 2 0 3 3 1 0 1 2 3 0 3 1 1 1 3 1 0 1 1 2 1 2 1 1 0 2 0 1 0 0 1 0 0 2
 0 0 1 3 2 0 2 0 0 1 2 0 2 1 2 1 0 0 3 1 1 2 1 1 2 0 2 0 1 2 1 1 0 3 0 0 1
 0 0 1 1 3 1 3 3 3 0 2 0 3 0 1 0 0 1 0 2 2 3 3 2 2 2 2 2 0 2 0 1 1 0 0 1 0
 0 1 3 1 0 2 3 0 1 1 0 0 2 2 2 1 2 0 2 0 2 0 2 2 2 3 0 1 0 0 2 1 1 1 0 0 1
 1 1 2 3 2 2 3 1 3 3 3 3 

# Training the SVM model on the Training set

In [20]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

# Predicting the Test set results

In [21]:
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix

In [22]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[121   3   0   0]
 [  4 103   3   0]
 [  0   6 114   5]
 [  0   0   2 139]]


0.954

# predicting test dataset

In [23]:
test_pred = classifier.predict(data_test)
print(test_pred)

[2 3 2 3 1 3 3 1 3 0 3 3 0 0 2 0 2 1 3 2 1 3 1 1 3 0 2 0 3 0 2 0 3 0 1 1 3
 1 2 1 1 2 0 0 0 1 0 3 1 2 1 0 3 0 3 0 3 1 0 3 3 3 0 1 1 1 2 3 1 2 1 2 2 3
 3 0 2 0 1 3 0 3 3 0 3 0 3 1 3 0 1 2 2 1 2 1 1 2 1 2 1 0 0 3 0 2 1 1 2 3 3
 3 1 3 3 3 3 2 3 0 0 3 2 1 2 0 3 2 2 2 0 2 1 1 3 1 1 0 3 2 1 2 1 3 2 3 3 3
 2 3 2 3 1 0 3 2 3 3 2 3 2 2 3 3 3 3 1 0 3 0 0 0 2 1 0 1 0 0 0 2 1 0 0 1 1
 2 2 1 0 0 0 1 0 3 1 0 2 2 2 3 1 1 2 2 3 2 2 1 0 0 1 2 0 2 3 3 0 2 0 3 2 3
 3 1 0 1 0 3 0 1 0 2 2 1 3 1 2 0 3 1 2 0 0 2 1 3 3 3 1 1 3 0 0 2 3 3 1 3 1
 1 3 2 1 2 3 3 3 1 0 0 2 3 1 1 3 2 1 3 0 0 3 1 0 3 2 3 3 2 1 3 3 2 3 1 2 1
 2 0 2 3 1 0 0 3 0 3 0 1 2 0 2 3 1 3 2 2 1 2 0 0 0 1 3 2 0 0 0 3 2 0 2 3 1
 2 2 2 3 1 3 3 2 2 2 3 3 0 3 1 3 1 3 1 2 3 0 1 0 3 1 3 2 3 0 0 0 0 2 0 0 2
 2 1 2 2 2 0 1 0 0 3 2 0 3 1 2 2 1 2 3 1 1 2 2 1 2 0 1 1 0 3 1 0 0 1 0 0 1
 1 0 1 0 2 2 3 2 3 0 3 0 3 0 1 1 0 2 0 3 2 3 3 1 3 1 3 1 2 2 0 1 2 1 1 0 0
 0 1 2 1 0 3 2 0 2 2 0 0 3 1 2 0 2 3 3 0 3 0 2 3 2 3 0 2 0 2 2 0 1 1 0 0 1
 2 1 3 3 3 2 3 1 2 2 3 3 

# Training the Kernel SVM model on the Training set

In [24]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

# Predicting the Test set results

In [25]:
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix

In [26]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[118   6   0   0]
 [  6  97   7   0]
 [  0  15 106   4]
 [  0   0  16 125]]


0.892

# predicting test dataset

In [27]:
test_pred = classifier.predict(data_test)
print(test_pred)

[2 3 2 3 1 3 3 1 3 0 3 3 0 0 2 0 2 1 3 2 1 3 1 1 3 0 2 0 2 0 2 0 3 0 1 1 3
 1 2 1 1 2 0 0 0 1 0 3 1 2 2 0 2 0 3 1 3 1 0 3 3 2 0 1 1 1 2 3 1 2 1 2 2 3
 3 0 2 0 2 3 0 3 3 0 3 0 2 1 3 0 1 1 2 1 2 1 0 2 1 3 1 0 0 3 0 2 0 1 2 3 3
 2 1 3 3 3 3 1 3 0 0 3 2 1 1 1 3 2 2 1 0 2 1 1 3 1 1 0 3 2 1 2 1 3 2 3 3 3
 2 3 2 3 1 0 3 2 3 3 2 3 3 2 3 3 3 3 1 0 3 0 0 0 1 1 0 1 0 0 1 2 1 0 0 1 1
 2 2 1 0 0 0 1 1 3 1 0 2 2 2 2 1 1 3 3 3 2 2 1 0 0 1 3 0 2 3 3 0 2 0 3 2 2
 3 1 0 1 0 3 0 1 0 2 2 1 3 1 2 0 3 1 2 0 0 2 1 2 2 3 1 1 3 0 0 2 3 3 1 3 1
 1 3 2 1 2 3 3 3 1 0 0 2 3 1 1 3 2 0 3 0 1 2 1 0 3 2 3 3 2 1 3 3 2 3 1 2 1
 1 0 2 3 1 0 0 3 0 3 0 1 2 0 2 3 1 3 2 2 0 3 0 0 0 1 3 2 0 1 0 3 1 0 3 3 1
 2 3 2 3 1 3 3 2 2 2 2 3 0 3 1 3 1 3 1 2 2 0 1 0 2 1 3 2 3 0 0 0 1 2 0 0 2
 2 1 2 2 2 0 1 0 0 3 2 0 3 1 2 2 1 2 3 1 1 2 1 1 2 0 1 1 0 3 2 0 0 1 0 0 1
 1 0 0 0 2 2 3 1 3 0 2 0 2 0 1 1 0 1 0 3 2 3 3 1 3 2 2 1 2 2 0 1 1 1 1 0 0
 0 1 2 1 0 3 3 0 2 2 0 0 3 1 1 0 2 2 3 0 3 0 2 3 2 3 0 2 0 2 2 0 1 1 0 0 1
 1 1 2 3 3 1 3 1 2 2 2 3 

# Training the Naive Bayes model on the Training set

In [28]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

# Predicting the Test set results

In [29]:
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix

In [30]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[117   7   0   0]
 [  6  83  21   0]
 [  0  22  92  11]
 [  0   0  11 130]]


0.844

# predicting test dataset

In [31]:
test_pred = classifier.predict(data_test)
print(test_pred)

[3 3 2 3 1 3 3 1 3 0 3 3 0 0 2 0 1 2 3 2 1 3 1 2 3 0 2 0 3 0 2 0 3 0 0 1 3
 1 2 2 1 2 0 0 0 0 1 2 1 2 2 0 2 0 3 0 3 1 1 3 3 3 1 1 1 1 1 2 1 1 1 1 2 3
 3 0 2 0 2 3 0 3 3 0 3 0 3 1 2 0 1 1 2 0 2 1 0 2 1 2 1 0 0 2 1 2 0 1 2 3 3
 3 1 3 3 3 3 1 3 0 0 3 2 1 1 0 3 2 2 1 0 1 1 2 3 1 1 0 3 2 1 2 2 2 3 3 3 2
 2 3 2 3 0 0 2 2 3 3 3 3 2 2 3 3 3 3 1 0 3 0 0 0 1 0 0 1 0 0 2 2 0 0 0 1 2
 2 1 1 0 0 0 0 0 3 1 0 2 1 2 3 1 2 2 3 3 1 2 1 0 1 2 2 1 2 3 3 0 2 0 3 2 2
 2 0 0 1 0 3 0 1 0 2 2 1 3 0 3 0 3 1 2 0 0 2 1 2 2 3 1 1 3 0 0 2 3 3 1 3 1
 0 3 2 1 2 3 3 3 1 0 1 1 3 1 1 3 2 0 3 0 1 2 0 0 3 2 3 2 2 1 3 2 2 3 2 2 1
 1 0 2 3 1 0 0 3 0 3 0 1 1 0 1 3 1 3 1 2 1 2 0 0 0 1 3 1 0 0 0 3 1 1 3 3 1
 2 3 2 3 1 3 3 2 2 2 3 3 0 3 0 3 1 3 1 3 3 0 1 1 3 1 3 1 3 0 0 0 0 2 0 1 1
 1 1 1 2 2 0 1 0 0 3 2 1 3 1 2 2 2 1 3 1 1 2 2 1 2 0 1 1 0 3 2 0 0 1 0 0 1
 0 0 0 0 2 2 3 2 3 0 3 1 3 0 1 1 1 2 0 3 2 3 3 1 3 1 3 1 3 2 1 2 2 2 1 0 0
 0 1 1 1 0 3 3 1 2 3 0 0 3 2 1 0 2 2 3 0 3 1 2 3 2 3 0 2 0 2 2 0 1 1 0 0 1
 1 2 2 3 3 2 3 1 1 2 2 3 

# Training the Decision Tree Classification model on the Training set

In [32]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

# Predicting the Test set results

In [33]:
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[110  14   0   0]
 [  9  92   9   0]
 [  0  13 102  10]
 [  0   0  15 126]]


0.86

# predicting test dataset

In [35]:
test_pred = classifier.predict(data_test)
print(test_pred)

[3 3 3 3 1 3 3 1 3 0 3 3 0 0 2 0 2 1 3 2 1 2 1 2 3 0 2 0 3 0 2 0 3 0 0 1 3
 1 2 1 1 1 0 0 0 1 0 3 1 2 1 0 3 0 3 1 3 1 1 3 3 2 0 1 1 1 2 3 1 2 1 2 2 3
 3 0 2 0 1 3 0 3 3 0 3 0 3 1 3 1 1 2 2 0 2 1 1 2 1 2 1 0 0 3 0 2 0 1 2 3 3
 2 1 3 3 3 3 1 3 0 0 2 1 1 2 0 3 2 3 1 0 2 1 1 3 0 1 0 3 2 1 3 1 3 2 3 3 2
 2 3 2 3 0 0 2 2 3 3 3 3 2 2 3 2 3 3 1 0 3 0 0 1 2 1 0 1 1 1 1 2 0 0 0 0 1
 2 2 1 0 0 0 1 0 3 2 0 2 2 2 3 1 1 2 3 3 2 2 1 0 0 1 2 0 2 3 3 0 2 0 3 2 2
 3 0 0 1 0 3 0 1 0 2 2 1 3 1 2 0 3 1 2 0 0 2 1 2 3 3 1 1 3 0 0 2 3 3 1 3 1
 1 3 2 1 2 3 3 3 1 0 0 2 3 1 1 3 2 0 3 0 1 2 1 0 3 2 3 2 2 1 3 3 2 3 2 2 1
 2 0 2 3 1 0 0 3 0 3 0 1 2 0 2 3 1 3 2 2 0 2 0 0 0 1 3 2 0 0 0 3 2 0 3 3 1
 2 2 2 3 1 3 3 1 2 2 3 3 0 3 1 3 1 3 1 3 3 0 2 1 3 1 3 2 3 0 0 0 0 2 0 0 2
 2 1 2 2 2 0 1 0 0 3 2 0 3 1 2 2 1 2 3 1 1 2 1 1 2 0 1 1 0 3 2 1 0 1 0 0 1
 0 0 1 0 2 2 3 2 3 0 2 0 3 0 1 1 1 1 0 3 2 3 3 1 3 1 2 2 2 2 0 1 1 1 1 0 0
 0 1 2 1 0 2 2 0 2 3 0 0 3 1 2 0 3 2 3 0 3 0 2 3 3 3 0 2 0 2 3 0 1 1 0 0 1
 1 1 3 3 3 1 3 1 2 2 2 3 

# Training the Random Forest Classification model on the Training set

In [36]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

# Predicting the Test set results

In [37]:
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix

In [38]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[120   3   1   0]
 [ 15  80  15   0]
 [  2  20  90  13]
 [  1   0  22 118]]


0.816

# predicting test dataset

In [39]:
test_pred = classifier.predict(data_test)
print(test_pred)

[2 2 2 3 1 3 3 1 3 0 3 3 0 0 2 0 1 1 3 1 1 3 1 1 3 0 2 0 2 0 2 0 3 0 0 1 3
 1 2 1 1 2 0 0 0 0 0 3 1 2 1 0 2 0 3 1 3 1 1 3 3 3 0 1 1 1 2 3 1 2 1 2 2 3
 3 0 2 0 1 3 1 3 3 0 3 0 2 1 2 0 1 1 2 1 2 1 0 2 1 2 1 0 0 3 0 2 0 1 2 3 3
 3 1 3 3 3 3 1 3 0 0 2 1 1 1 0 3 2 3 1 0 1 1 0 3 0 1 0 3 2 1 3 1 3 2 3 3 3
 0 3 3 3 1 0 3 2 3 3 3 3 3 2 3 2 3 3 1 0 3 0 0 0 1 1 0 2 0 0 0 2 1 0 0 1 2
 2 2 1 0 0 0 0 1 3 1 0 2 1 2 3 1 2 2 3 3 1 2 1 0 0 1 3 0 3 3 3 0 2 0 3 1 2
 3 0 0 2 0 3 0 1 0 2 1 0 3 0 2 0 3 1 2 0 0 2 1 3 3 3 1 1 3 0 0 2 3 3 1 3 1
 1 3 2 0 2 3 3 3 1 0 1 1 3 1 1 3 1 1 3 0 1 2 0 0 3 2 2 2 2 1 3 3 2 3 1 2 1
 2 0 2 3 1 0 0 3 0 3 0 0 2 0 1 3 1 3 1 2 1 2 0 0 1 1 3 1 0 1 0 2 1 0 2 3 0
 2 3 2 3 1 3 3 2 2 2 2 3 0 3 0 2 1 3 1 2 3 0 1 0 2 1 3 1 3 0 0 0 0 2 0 0 1
 1 1 1 2 2 0 1 0 0 3 2 0 3 1 2 2 1 1 3 1 1 2 3 1 2 0 1 1 0 3 2 1 0 1 0 0 1
 0 0 0 0 2 2 3 3 3 0 2 0 3 0 2 1 0 2 0 3 2 3 3 1 3 1 2 1 2 2 0 2 2 1 2 0 0
 0 1 2 1 0 3 2 0 1 3 0 0 3 0 1 0 3 2 3 0 2 0 2 3 2 3 0 2 0 2 2 0 1 1 0 0 1
 1 1 3 3 3 2 3 1 1 2 2 3 